### PR TITLE
updates to make more compatible with later api versions

### PR DESCRIPTION
**Pull request by kylewetherald**
versions v12+ have a different address format and require extra headers.
also added support for ip, email, and transaction tag

### CODE REVIEW

**Comment by VinceG** [comment]
@kylewetherald thank you.

**Comment by VinceG** [comment]
@kylewetherald oh snap, i just realized i haven't tested the new additions. this is tested right? i'll have to revert otherwise until it's confirmed.

**Comment by kylewetherald** [comment]
I did the implicit tests of using it. I didn't write any unit tests or anything though.

**Comment by VinceG** [comment]
@kylewetherald there are no unit tests in this project anyways. i'll just keep it for now. i'll track to see if anyone reports any issues in the future.

**Comment by kylewetherald** [comment]
Sounds good. Thanks.

On Mon, Mar 16, 2015 at 3:32 PM, Vincent Gabriel <notifications@github.com>
wrote:

> @kylewetherald <https://github.com/kylewetherald> there are no unit tests
> in this project anyways. i'll just keep it for now. i'll track to see if
> anyone reports any issues in the future.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/VinceG/php-first-data-api/pull/13#issuecomment-81888639>
> .
>



-- 

   - Kyle Wetherald
   - Software Engineer
   - ShowClix

**Pull request merged**
